# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
# æ ‡ç­¾é¡µå›¾æ ‡ï¼Œå›¾åƒå¿…é¡»æ”¾åœ¨staticä¸­
favicon = "/titleImg.png"


# ç‰ˆæƒä¿¡æ¯
[footer]
since = 2024
# æ–‡æœ¬
customText = "Special Thanks to Yukari Chan"

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "ğŸ˜½"
subtitle = "å‘†å¤´å‘†è„‘çš„å¤§èªæ˜ã€‚åœ¨æ­¤åˆ†äº«ä¸€äº›æ¯”è¾ƒä¸ªäººåŒ–çš„å†…å®¹ã€‚"

[sidebar.avatar]
# æ˜¯å¦å¯ç”¨å¤´åƒ
enabled = true
# æ˜¯å¦æ˜¯æœ¬åœ°å›¾åƒ
local = true
# å¤´åƒï¼Œå¿…é¡»æ”¾åœ¨assets/imgä¸­ã€‚
src = "img/file_259987.jpg"

# æ–‡ç« å…¨å±€é…ç½®
[article]
# æ˜¯å¦å¯ç”¨KaTeX
math = false
# æ€»é˜…è¯»æ—¶é•¿
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets å³ä¾§å°éƒ¨ä»¶çš„é…ç½®
[[widgets.homepage]]
# typeæ˜¯éƒ¨ä»¶åç§°
type = "search"

# å½’æ¡£å°éƒ¨ä»¶
[[widgets.homepage]]
type = "archives"

# å½’æ¡£æ çš„æ•°é‡é™åˆ¶
[widgets.homepage.params]
# 
limit = 5

[[widgets.homepage]]
type = "categories"

# å³ä¾§åˆ†ç±»æœ€å¤§å±•ç¤ºæ•°
[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"
# å³ä¾§æ ‡ç­¾æ•°é‡é™åˆ¶
[widgets.homepage.params]
limit = 10

# æ˜¾ç¤ºé¡µé¢ç›®å½•çš„ç»„ä»¶
[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

# é…è‰²æ–¹æ¡ˆ light or dark
[colorScheme]
# æ˜¾ç¤ºåˆ‡æ¢æŒ‰é’®
toggle = true
# é»˜è®¤é…è‰² light|dark|autoï¼Œautoæ ¹æ®ç”¨æˆ·ç³»ç»Ÿå†³å®š
default = "auto"


# hugoå†…ç½®çš„å›¾å½¢å¤„ç†åŠŸèƒ½ï¼Œå¯ä»¥å¯¹å›¾åƒè‡ªåŠ¨ç¼©æ”¾è°ƒæ•´å¤§å°
[imageProcessing.cover]
enabled = true

# å¯¹æ–‡ç« ä¸­çš„å›¾åƒå¯ç”¨å¤„ç†åŠŸèƒ½
[imageProcessing.content]
enabled = true

## Comments å„è¯„è®ºç³»ç»Ÿçš„é…ç½®
[comments]
# å¯ç”¨
enabled = true
# è¯„è®ºç³»ç»Ÿçš„é€‰æ‹©
provider = "disqus"

# è¯¦ç»†é…ç½®
[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = ""
lang = ""
visitor = ""
avatar = ""
emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
requiredMeta = ["name", "email", "url"]
placeholder = ""

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = ""
repoID = ""
category = ""
categoryID = ""
mapping = ""
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0

[comments.gitalk]
owner = "CHmadoka"
admin = ""
repo = ""
clientID = ""
clientSecret = ""

[comments.cusdis]
host = ""
id = ""
